Language fix - minor EN language errors
TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted pull request #191
Opened 2022-03-22 18:20 UTC by sarahmccarthy123

2022-03-24 07:46 UTC, mbrodala requested changes

2022-03-24 07:46 UTC, mbrodala commented on Documentation/Troubleshooting/TYPO3.rst
> +the password. Note that only backend users with administrative rights can
```suggestion
When the password for a backend user needs to be reset, log into the backend as a
different user and use the :guilabel:`System > Backend Users` tool to reset
the password. Note that only backend users with administrative rights can
```

2022-03-24 07:46 UTC, mbrodala commented on Documentation/Troubleshooting/TYPO3.rst
> +appropriate access, access the Install Tool directly
```suggestion
appropriate access, open the Install Tool directly
```

Here _access, access_ sounds weird. ;-)

2022-03-24 07:46 UTC, mbrodala commented on Documentation/Troubleshooting/TYPO3.rst
> +and select :guilabel:`Create Administrator`. In this dialog box you
```suggestion
and select :guilabel:`Create Administrator`. Here you
```

2022-03-24 07:46 UTC, mbrodala commented on Documentation/Troubleshooting/TYPO3.rst
> +The following TypoScript setting can also be added into the root template for
```suggestion
The following TypoScript setting can also be added to the root template for
```

2022-03-24 07:46 UTC, mbrodala commented on Documentation/Troubleshooting/TYPO3.rst
> +   Once debugging has been completed, make sure you remove any debug Typoscript and
```suggestion
   Once debugging has been completed, remove any debug TypoScript and
```

2022-03-24 07:46 UTC, mbrodala commented on Documentation/Troubleshooting/TYPO3.rst
> +concatenated in the order that they are loaded. Therefore including one of
```suggestion
concatenated in their loading order. Therefore including one of
```

2022-04-03 07:45 UTC, flicstar commented
Thanks heaps @sarahmccarthy123 for your work on this! I have reviewed and I think if we can incorporate @mbrodala's suggested changes, we're good to go 👍

2022-04-03 09:09 UTC, linawolf approved these changes

2022-04-03 10:21 UTC, sarahmccarthy123 reviewed
Yes this all looks fine :-)

2022-04-04 07:32 UTC, mbrodala approved these changes

2022-04-04 07:32 UTC, merged