Tutorial: Install TYPO3 on DDEV
TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted pull request #237
Opened 2022-08-30 15:42 UTC by linawolf

releases: main, 11.5

2022-08-30 17:35 UTC, brotkrueml requested changes

2022-08-30 17:35 UTC, brotkrueml commented on Documentation/Installation/Index.rst
> +            DDev, Docker and Composer.
```suggestion
            DDEV, Docker and Composer.
```

As it writes itself: https://ddev.readthedocs.io/en/stable/

2022-08-30 17:35 UTC, brotkrueml commented on Documentation/Installation/TutorialDdev.rst
> +            Docroot Location (current directory):public
```suggestion
            Docroot Location (current directory): public
```

2022-08-30 17:35 UTC, brotkrueml commented on Documentation/Installation/TutorialDdev.rst
> +        (who is also system maintainer).
Maybe link "system maintainer", not everyone may know, what that is: https://docs.typo3.org/m/typo3/tutorial-getting-started/11.5/en-us/UserManagement/BackendPrivileges/Index.html#system-maintainers

2022-08-30 17:35 UTC, brotkrueml commented on Documentation/Installation/TutorialDdev.rst
> +If you want to all projects from running on DDEV you can call:
This sentence sounds strange. Maybe: "If you want to stop all DDEV projects ..."

2022-08-30 17:35 UTC, brotkrueml commented on Documentation/Installation/TutorialDdev.rst
> +If you want to delete the project you just deleted you can delete it by
```suggestion
If you want to delete the project you just created you can delete it by
```
A little bit "delete" too often.

2022-08-30 17:35 UTC, brotkrueml commented on Documentation/Installation/TutorialDdev.rst
> +calling the following in your new projects root folder:
```suggestion
calling the following command in your new projects root folder:
```

2022-08-30 18:46 UTC, linawolf commented on Documentation/Installation/TutorialDdev.rst
> +If you want to all projects from running on DDEV you can call:
```suggestion
If you want to stop all projects from running on DDEV you can call:
```

2022-08-30 18:46 UTC, linawolf commented on Documentation/Installation/TutorialDdev.rst
> +        (who is also system maintainer).
```suggestion
        (who is also :ref:`system maintainer <system-maintainer>`).
```

2022-08-30 19:02 UTC, brotkrueml commented on Documentation/Installation/TutorialDdev.rst
> +Preparations to install DDev
```suggestion
Preparations to install DDEV
```

2022-08-30 19:03 UTC, brotkrueml commented on Documentation/Installation/TutorialDdev.rst
> +        #.  Create a file called FIRST_INSTALL in your webroot
```suggestion
        #.  Create a file called :file:`FIRST_INSTALL` in your webroot
```

2022-08-30 19:04 UTC, brotkrueml approved these changes

2022-08-30 19:27 UTC, linawolf commented
Let us wait for the review of @tomwarwick please

2022-09-06 13:07 UTC, linawolf commented on Documentation/Installation/TutorialDdev.rst
> +DDEV modified :file:`public/typo3conf/AdditionalConfiguration.php`
Actually DDEV creates this file. If there would have been an AdditionalConfiguration already, DDEV would not have modified it

2022-09-06 13:09 UTC, linawolf commented on Documentation/Installation/TutorialDdev.rst
> +The projects will stay configured and the database will be persisted.
shall we use plural databases? Each project has its own database

2022-09-06 13:09 UTC, linawolf commented on Documentation/Installation/TutorialDdev.rst
> +If you want to delete the project you just created you can delete it by
delete.. delete... the sentence sounds strange...

2022-09-06 13:09 UTC, linawolf commented on Documentation/Installation/TutorialDdev.rst
> +During the installation setup process TYPO3 created all the tables it needed. If you want to have a look at the database, you can run the following command:
Line to long

2022-09-07 08:58 UTC, tomwarwick approved these changes

2022-09-07 08:58 UTC, merged